server.port=9015
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb
=======

spring.datasource.url=jdbc:mysql://localhost:3306/SDC_backend
>>>>>>> 13913549b7d1085aba9eae7f4c2ce8f7600eb511
spring.datasource.username=root
spring.datasource.password=mayuresh@123root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
